<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[From xl:Akshara]]>
    </line>
    <line>
      <![CDATA[Test Automation Training - Java, Selenium, API Automation]]>
    </line>
    <line>
      <![CDATA[CONTACT US]]>
    </line>
    <line>
      <![CDATA[Test:testA Failed and ScreenShot has been taken:.\screenshots\testA.png]]>
    </line>
    <line>
      <![CDATA[From xl:Akshara]]>
    </line>
    <line>
      <![CDATA[Test Automation Training - Java, Selenium, API Automation]]>
    </line>
    <line>
      <![CDATA[CONTACT US]]>
    </line>
    <line>
      <![CDATA[Test:testA Failed and ScreenShot has been taken:.\screenshots\testA.png]]>
    </line>
  </reporter-output>
  <suite started-at="2022-12-30T00:29:55 IST" name="Suite" finished-at="2022-12-30T00:30:17 IST" duration-ms="21674">
    <groups>
    </groups>
    <test started-at="2022-12-30T00:29:55 IST" name="TestLocal" finished-at="2022-12-30T00:30:11 IST" duration-ms="15789">
      <class name="script.Test1">
        <test-method is-config="true" signature="openApp(java.lang.String)[pri:0, instance:script.Test1@459e9125]" started-at="2022-12-30T00:29:55 IST" name="openApp" finished-at="2022-12-30T00:30:08 IST" duration-ms="12912" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[config.properties]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testA()[pri:0, instance:script.Test1@459e9125]" started-at="2022-12-30T00:30:08 IST" name="testA" finished-at="2022-12-30T00:30:09 IST" duration-ms="1086" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [CONTACT U] but found [CONTACT US]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [CONTACT U] but found [CONTACT US]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at script.Test1.testA(Test1.java:29)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[From xl:Akshara]]>
            </line>
            <line>
              <![CDATA[Test Automation Training - Java, Selenium, API Automation]]>
            </line>
            <line>
              <![CDATA[CONTACT US]]>
            </line>
          </reporter-output>
        </test-method> <!-- testA -->
        <test-method is-config="true" signature="closeApp(org.testng.ITestResult)[pri:0, instance:script.Test1@459e9125]" started-at="2022-12-30T00:30:09 IST" name="closeApp" finished-at="2022-12-30T00:30:11 IST" duration-ms="1700" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testA status=FAILURE method=Test1.testA()[pri:0, instance:script.Test1@459e9125] output=From xl:Akshara]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Test:testA Failed and ScreenShot has been taken:.\screenshots\testA.png]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- script.Test1 -->
    </test> <!-- TestLocal -->
    <test started-at="2022-12-30T00:29:55 IST" name="TestRemote" finished-at="2022-12-30T00:30:17 IST" duration-ms="21674">
      <class name="script.Test1">
        <test-method is-config="true" signature="openApp(java.lang.String)[pri:0, instance:script.Test1@477b4cdf]" started-at="2022-12-30T00:29:55 IST" name="openApp" finished-at="2022-12-30T00:30:14 IST" duration-ms="18832" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[qa.properties]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testA()[pri:0, instance:script.Test1@477b4cdf]" started-at="2022-12-30T00:30:14 IST" name="testA" finished-at="2022-12-30T00:30:14 IST" duration-ms="365" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [CONTACT U] but found [CONTACT US]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [CONTACT U] but found [CONTACT US]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at script.Test1.testA(Test1.java:29)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[From xl:Akshara]]>
            </line>
            <line>
              <![CDATA[Test Automation Training - Java, Selenium, API Automation]]>
            </line>
            <line>
              <![CDATA[CONTACT US]]>
            </line>
          </reporter-output>
        </test-method> <!-- testA -->
        <test-method is-config="true" signature="closeApp(org.testng.ITestResult)[pri:0, instance:script.Test1@477b4cdf]" started-at="2022-12-30T00:30:15 IST" name="closeApp" finished-at="2022-12-30T00:30:17 IST" duration-ms="2389" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testA status=FAILURE method=Test1.testA()[pri:0, instance:script.Test1@477b4cdf] output=From xl:Akshara]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Test:testA Failed and ScreenShot has been taken:.\screenshots\testA.png]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- script.Test1 -->
    </test> <!-- TestRemote -->
  </suite> <!-- Suite -->
</testng-results>
